bump git-recent

diff --git a/bin/git-recent b/bin/git-recent
--- a/bin/git-recent
+++ b/bin/git-recent
@@ -1,8 +1,5 @@
-#!/usr/bin/env bash
-# See: (MIT)
-# https://github.com/paulirish/git-recent/blob/1bf058113970eaf40bafdb0d803e85672d9422ea/git-recent
-#
-
+#!/bin/bash
+# See: https://github.com/paulirish/git-recent/blob/d5f63cf328d79170f6505451804831b5e5726c3d/git-recent
 #
 # git recent 2.0 - switching branches, but so fancy
 #
@@ -16,6 +13,8 @@ if ! command -v fzf >/dev/null 2>&1; then
   echo "Error: fzf is not installed. Please install fzf to use git-recent." >&2
   exit 1
 fi
+[ "$(git rev-parse --is-inside-work-tree)" = "true" ] || exit
+
 if [[ "$1" == "--help" ]]; then
   echo "git-recent: Browse and checkout recently used Git branches."
   echo
@@ -31,19 +30,30 @@ fi
 branches_format="%(color:yellow)%(refname:short)%(color:reset)"
 commits_format="%C(red bold)%h %C(bold blue)%an %C(bold green)%ad %Creset%s"
 
-# The primary branch (eg main or master or w/e)
-origin_HEAD=$(cat $(git rev-parse --show-cdup).git/refs/remotes/origin/HEAD | awk '{print $2}')
+# The HEAD of the primary branch (eg main or master or w/e), for diffing.
+# TODO: some branch mgmt approaches don't work well with this. And may prefer `git log --pretty=format:%H --merges -n 1`.  See https://github.com/paulirish/git-recent/issues/28
+diff_base=$(cat $(git rev-parse --show-cdup).git/refs/remotes/origin/HEAD | awk '{print $2}')
 
-uniqcommits_cmd="git log --date=human --color=always --format='$commits_format' --no-merges $origin_HEAD..{1}"
-COLUMNS=$(tput cols)
+uniqcommits_cmd="git log --date=human --color=always --format='$commits_format' --no-merges $diff_base..{1}"
 
-
-diffbranch_cmd="git diff --color=always $origin_HEAD...{}"
+diffbranch_cmd="git diff --color=always $diff_base...{}"
 # Progressive enhancement if you have delta or diff-so-fancy
 if command -v delta >/dev/null 2>&1; then
-  diffbranch_cmd="$diffbranch_cmd | delta --file-style=omit --width=${FZF_PREVIEW_COLUMNS:-$COLUMNS}"
+  diffbranch_cmd="$diffbranch_cmd | delta"
 elif command -v diff-so-fancy >/dev/null 2>&1; then
   diffbranch_cmd="$diffbranch_cmd | diff-so-fancy"
+fi
+
+# Copy to clipboard, variants for mac/linux
+copy_cmd="echo 'Could not copy {} to clipboard.'"
+if command -v pbcopy >/dev/null; then
+  copy_cmd="printf '%s' {} | pbcopy"
+elif command -v wl-copy >/dev/null; then
+  copy_cmd="printf '%s' {} | wl-copy"
+elif command -v xclip >/dev/null; then
+  copy_cmd="printf '%s' {} | xclip -selection clipboard"
+elif command -v xsel >/dev/null; then
+  copy_cmd="printf '%s' {} | xsel --clipboard"
 fi
 
 # if extra arg passed (eg `git recent remotename`), then list those remote branches, rather than local ones
@@ -54,21 +64,28 @@ fi
 # - https://github.com/junegunn/fzf/wiki/Examples-(fish)#git
 # - https://github.com/junegunn/fzf-git.sh (intense.)
 
+# If there's a GIT_RECENT_QUERY environment variable, use it for non-interactive filtering. (Primarily added for testing.)
+filterarg=${GIT_RECENT_QUERY:+"--filter=$GIT_RECENT_QUERY"}
+
 _browse_branches() {
   git for-each-ref --color=always --sort=-authordate "$heads" --format="$branches_format" \
-    |  fzf --ansi -- \
-        --layout=reverse --multi --height=90% --min-height=20  \
+    |  fzf  \
+        $filterarg --ansi -- --layout=reverse --multi --height=90% --min-height=20  \
         --border-label-pos=2 --border-label '🌲 Branches' --border \
         --no-hscroll --no-multi \
-        --preview-window='up,70%,border-left,border-rounded' --preview="$uniqcommits_cmd" --preview-label="Commits unique to branch" \
-        --header $'ENTER (checkout)\nCTRL-O (show branch diff)\n' \
+        --preview-window='right,70%,border-left,border-rounded' --preview="$uniqcommits_cmd" --preview-label="Commits unique to branch" \
+        --header $'ENTER (checkout)\nCTRL-O (show branch diff)\nCTRL-Y (copy name to clipboard)' \
         --bind 'preview-scroll-up:preview-up+preview-up+preview-up' \
         --bind 'preview-scroll-down:preview-down+preview-down+preview-down' \
+        --bind "ctrl-y:execute-silent($copy_cmd)" \
         --bind "ctrl-o:preview:$diffbranch_cmd"
 }
-
 chosen_branch="$(_browse_branches)"
-if [[ -n "$chosen_branch" ]]; then
+line_count=$(printf "%s" "$chosen_branch" | wc -l)
+
+if [[ -n "$chosen_branch" ]] && (( line_count == 0 )); then
   echo git checkout "$chosen_branch"
   git checkout "$chosen_branch"
+else
+  echo "$chosen_branch"
 fi
